services:
  oj-redis:
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ./data/redis:/data
    deploy:
      resources:
        limits:
          memory: 256M

  oj-postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
    deploy:
      resources:
        limits:
          memory: 512M

  oj-judge:
    image: registry.cn-hongkong.aliyuncs.com/oj-image/judge:1.6.1
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data/backend/test_case:/test_case:ro
      - ./data/judge_server/log:/log
      - ./data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://oj-judge:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
          pids: 128

  oj-backend:
    image: registry.cn-hongkong.aliyuncs.com/oj-image/backend:1.6.1
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - oj-judge
    volumes:
      - ./data/backend:/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=CHANGE_THIS
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oj-${SLUG:-main}.rule=Host(`oj-${SLUG:-main}.mangagaki.net`) || Host(`oj.mangagaki.net`)"
      - "traefik.http.services.oj-${SLUG:-main}.loadbalancer.server.port=8000"
    networks:
      - default
      - traefik-net
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M

networks:
  traefik-net:
    external: true
