name: Deploy OJ

on:
  push:
  delete:

permissions:
  statuses: write

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: self-hosted
    environment:
      name: ${{ github.ref_name }}
      url: https://oj-${{ github.ref_name }}.mangagaki.net
    steps:
      - uses: actions/checkout@v4

      - name: Set env
        run: |
          SLUG=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9]/-/g')
          echo "SLUG=$SLUG" >> $GITHUB_ENV

      - name: Deploy
        working-directory: /Users/yang/oj
        run: |
          git fetch origin
          git checkout ${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}
          SLUG=${{ env.SLUG }} docker compose -p oj-${{ env.SLUG }} up -d --build

      - name: Add deployment link
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              target_url: 'https://oj-${{ env.SLUG }}.mangagaki.net',
              description: 'Deployment live',
              context: '🚀 Preview'
            })

  teardown:
    if: github.event_name == 'delete' && github.event.ref_type == 'branch'
    runs-on: self-hosted
    steps:
      - name: Remove instance
        run: |
          SLUG=$(echo "${{ github.event.ref }}" | sed 's/[^a-zA-Z0-9]/-/g')
          docker compose -p oj-$SLUG down -v
